package com.luog.onlinemusic.entity.commons;
// Generated Jan 31, 2018 11:31:17 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "online_music")
public class Account implements java.io.Serializable {

	private String username;
	private Role role;
	private String password;
	private Date dateOfBirth;
	private Date createdTime;
	private String gender;
	private String phone;
	private boolean status;
	private String photo;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<PlayList> playLists = new HashSet<PlayList>(0);

	public Account() {
	}

	public Account(String username, Role role, String password, Date dateOfBirth, Date createdTime, String gender,
			String phone, boolean status) {
		this.username = username;
		this.role = role;
		this.password = password;
		this.dateOfBirth = dateOfBirth;
		this.createdTime = createdTime;
		this.gender = gender;
		this.phone = phone;
		this.status = status;
	}

	public Account(String username, Role role, String password, Date dateOfBirth, Date createdTime, String gender,
			String phone, boolean status, String photo, Set<Comment> comments, Set<PlayList> playLists) {
		this.username = username;
		this.role = role;
		this.password = password;
		this.dateOfBirth = dateOfBirth;
		this.createdTime = createdTime;
		this.gender = gender;
		this.phone = phone;
		this.status = status;
		this.photo = photo;
		this.comments = comments;
		this.playLists = playLists;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "gender", nullable = false, length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "photo", length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<PlayList> getPlayLists() {
		return this.playLists;
	}

	public void setPlayLists(Set<PlayList> playLists) {
		this.playLists = playLists;
	}

}
