package com.luog.onlinemusic.entity.commons;
// Generated Jan 31, 2018 11:31:17 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "online_music")
public class Album implements java.io.Serializable {

	private Integer id;
	private String name;
	private String photo;
	private Date releasedTime;
	private Set<AlbumSinger> albumSingers = new HashSet<AlbumSinger>(0);
	private Set<AlbumSong> albumSongs = new HashSet<AlbumSong>(0);

	public Album() {
	}

	public Album(String name, Date releasedTime) {
		this.name = name;
		this.releasedTime = releasedTime;
	}

	public Album(String name, String photo, Date releasedTime, Set<AlbumSinger> albumSingers,
			Set<AlbumSong> albumSongs) {
		this.name = name;
		this.photo = photo;
		this.releasedTime = releasedTime;
		this.albumSingers = albumSingers;
		this.albumSongs = albumSongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "photo", length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "released_time", nullable = false, length = 10)
	public Date getReleasedTime() {
		return this.releasedTime;
	}

	public void setReleasedTime(Date releasedTime) {
		this.releasedTime = releasedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<AlbumSinger> getAlbumSingers() {
		return this.albumSingers;
	}

	public void setAlbumSingers(Set<AlbumSinger> albumSingers) {
		this.albumSingers = albumSingers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<AlbumSong> getAlbumSongs() {
		return this.albumSongs;
	}

	public void setAlbumSongs(Set<AlbumSong> albumSongs) {
		this.albumSongs = albumSongs;
	}

}
