package com.luog.onlinemusic.entity.commons;
// Generated Jan 31, 2018 11:31:17 AM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "online_music")
public class Author implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date dateOfBirth;
	private String gender;
	private String description;
	private String photo;
	private Set<AuthorDetail> authorDetails = new HashSet<AuthorDetail>(0);

	public Author() {
	}

	public Author(String name, Date dateOfBirth, String gender, String description) {
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.description = description;
	}

	public Author(String name, Date dateOfBirth, String gender, String description, String photo,
			Set<AuthorDetail> authorDetails) {
		this.name = name;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.description = description;
		this.photo = photo;
		this.authorDetails = authorDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "gender", nullable = false, length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "photo", length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<AuthorDetail> getAuthorDetails() {
		return this.authorDetails;
	}

	public void setAuthorDetails(Set<AuthorDetail> authorDetails) {
		this.authorDetails = authorDetails;
	}

}
