package com.luog.onlinemusic.entity.commons;
// Generated Jan 31, 2018 11:31:17 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlayListDetail generated by hbm2java
 */
@Entity
@Table(name = "play_list_detail", catalog = "online_music")
public class PlayListDetail implements java.io.Serializable {

	private Integer id;
	private PlayList playList;
	private Song song;

	public PlayListDetail() {
	}

	public PlayListDetail(PlayList playList, Song song) {
		this.playList = playList;
		this.song = song;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "play_list_id", nullable = false)
	public PlayList getPlayList() {
		return this.playList;
	}

	public void setPlayList(PlayList playList) {
		this.playList = playList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id", nullable = false)
	public Song getSong() {
		return this.song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

}
